name: 'Jest Coverage Commenter'
description: 'Comment on PRs with Jest Coverage Information'
author: 'Derek Kershner'
inputs:
  github_token:
    description: 'A GitHub Token, the standard one is great'
    required: true
  test_command:
    description: 'The test command to run, that also runs coverage appropriately'
    default: 'npx jest --coverage'
    required: false
  reporter:
    description: 'Possible types: text, text-summary. Set your --coverageReporters to match.'
    default: 'text'
    required: false
  comment_prefix:
    description: 'A message desired to be shown before the code coverage report'
    default: '## Jest Coverage'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: percent
  color: orange