name: Merging to Master

on:
  push:
    branches: [master]

jobs:
  master-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Tag commit with updated version
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ steps.extract_version.outputs.version }}"
      - name: Update release tags for latest major and minor releases
        uses: haya14busa/action-update-semver@v1
        with:
          tag: "v${{ steps.extract_version.outputs.version }}"